# Generated by Django 3.2 on 2021-05-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion_Forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='link',
            field=models.CharField(max_length=100),
        ),
    ]
