# Generated by Django 3.2.3 on 2021-05-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion_Forum', '0002_alter_forum_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='name',
            field=models.CharField(default='anonymous', max_length=200),
        ),
        migrations.AlterField(
            model_name='forum',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='forum',
            name='link',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
