# Generated by Django 3.2.3 on 2021-05-17 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion_Forum', '0003_auto_20210514_1440'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Discussion',
            new_name='Comments',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='discuss',
            new_name='comment',
        ),
    ]
