# Generated by Django 4.1.7 on 2023-02-26 11:04

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion_Forum', '0005_auto_20210517_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='discuss',
            field=martor.models.MartorField(),
        ),
        migrations.AlterField(
            model_name='forum',
            name='description',
            field=martor.models.MartorField(),
        ),
    ]
