# Generated by Django 4.1.7 on 2023-02-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion_Forum', '0006_alter_discussion_discuss_alter_forum_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='discuss',
            field=models.CharField(max_length=1000),
        ),
    ]
