# Generated by Django 4.1.7 on 2023-02-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion_Forum', '0008_alter_forum_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='name',
            field=models.TextField(default='anonymous', max_length=200),
        ),
        migrations.AlterField(
            model_name='forum',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
