# Generated by Django 4.1.7 on 2023-02-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion_Forum', '0009_alter_discussion_name_alter_forum_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='discuss',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='name',
            field=models.CharField(default='anonymous', max_length=200),
        ),
    ]
