# Generated by Django 3.2.18 on 2023-02-28 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion_Forum', '0010_alter_discussion_discuss_alter_discussion_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion',
            old_name='discuss',
            new_name='comment',
        ),
    ]
